spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8721
        dashboard: localhost:8080
      eager: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/alibaba/**
server:
  port: 9000

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: debug
